language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_4ff59711fb18_key -iv $encrypted_4ff59711fb18_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d